# Generated by Django 4.2.7 on 2023-12-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0002_alter_competidor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrequi',
            name='posicion',
            field=models.PositiveIntegerField(default=1, verbose_name='Posicion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('6', 'AB-'), ('5', 'AB+'), ('8', 'O-'), ('7', 'O+')], verbose_name='Tipo de Sangre'),
        ),
    ]
