# Generated by Django 4.2.7 on 2023-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0003_carrequi_posicion_alter_competidor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='estado',
            field=models.CharField(choices=[('1', 'finalizada'), ('0', 'Sin Correr')], default='Sin Correr', max_length=15, verbose_name='Estado de la carrera'),
        ),
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('2', 'A-'), ('6', 'AB-'), ('7', 'O+'), ('1', 'A+'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('8', 'O-')], verbose_name='Tipo de Sangre'),
        ),
    ]
