# Generated by Django 4.2.7 on 2023-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0004_carrera_estado_alter_competidor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('2', 'A-'), ('1', 'A+'), ('7', 'O+'), ('8', 'O-'), ('6', 'AB-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+')], verbose_name='Tipo de Sangre'),
        ),
    ]
